# Generated by Django 5.2.12 on 2026-03-23 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название достижения')),
                ('icon_class', models.CharField(default='fas fa-medal', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Очки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сообщества')),
                ('icon_class', models.CharField(default='fas fa-users', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Длительность (недель)')),
                ('lessons_count', models.PositiveIntegerField(default=10, verbose_name='Количество уроков')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (₽)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (₽)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('icon_class', models.CharField(default='fas fa-language', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('badge_text', models.CharField(blank=True, help_text='Например: "🔥 АКЦИЯ"', max_length=50, verbose_name='Текст бейджа')),
                ('badge_color', models.CharField(default='warning', max_length=20, verbose_name='Цвет бейджа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('content', models.TextField(blank=True, help_text='HTML формат', verbose_name='Содержание урока')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Длительность (минут)')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Бесплатный просмотр')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Всего очков')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Пройдено уроков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
